#!/usr/bin/env bash

export DOTNET_ROOT=/app/lib/dotnet

WAYLAND_SOCKET=${WAYLAND_DISPLAY:-"wayland-0"}

if [[ -e "${XDG_RUNTIME_DIR}/${WAYLAND_SOCKET}" || -e "${WAYLAND_DISPLAY}" ]]
then
    EXTRA_ARGS="--enable-wayland-ime --ozone-platform-hint=auto"
fi

/app/extra/storageexplorer/StorageExplorer ${EXTRA_ARGS}
